#:schema node_modules/wrangler/config-schema.json
name = "blogger-pwa-github"
main = "./src/workers/github-workers.ts"
compatibility_date = "2024-06-22"
compatibility_flags = [ "nodejs_compat" ]
upload_source_maps = true

[dev]
port = 8080

[vars]
CF_ENV = "local"

[env.production]
minify = true

[env.production.vars]
CF_ENV = "production"
