name: Push Generated Bucket and Deploy

on:
  push:
  create:
  repository_dispatch:

env:
  NODE_VERSION: "22.12.0"
  NPM_VERSION: "10.9.0"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      deployments: write
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Install Node.js
      - name: Setup Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

        # Install NPM
      - name: Setup NPM v${{ env.NPM_VERSION }}
        run: npm install -g npm@${{ env.NPM_VERSION }}

        # Install the dependencies
      - name: Install Dependencies
        run: npm install

        # Generate bucket and output files to proceed further
      - name: Generate Bucket and Output
        run: npm run generate -- --repository=${{ github.repository }} --branch=${{ github.head_ref || github.ref_name }}

        # Deploy to cloudflare workers if default branch and required secrets (CLOUDFLARE_ACCOUNT_ID and CLOUDFLARE_API_TOKEN) exist
      - name: Deploy to Cloudflare Workers
        if: ${{ ((github.head_ref || github.ref_name) == github.event.repository.default_branch) && (env.CLOUDFLARE_ACCOUNT_ID != '') && (env.CLOUDFLARE_API_TOKEN != '') }}
        run: |
          npx wrangler deploy --config wrangler.kv.json --env production
          npx wrangler deploy --config wrangler.github.json --env production

        # Commit all changed files back to the repository
      - name: Push Generated Bucket and Output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_options: "--allow-empty"
          commit_message: |
            update: generate bucket and output
            Triggered by ${{ github.sha }}
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
