on: [push]

name: Generate Bucket and Output

env:
  NODE_VERSION: "20.14.0"
  NPM_VERSION: "10.7.0"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup NPM v${{ env.NPM_VERSION }}
        run: npm install -g npm@${{ env.NPM_VERSION }}

      - name: Install Dependencies
        run: npm install

      - name: Generate bucket and output
        run: npm run generate -- --repository=${{ github.repository }} --branch=${{ github.head_ref || github.ref_name }}

        # Commit all changed files back to the repository
      - name: Push generated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          commit_options: "--allow-empty"
          commit_message: |
            update: generated bucket and output
            Triggered by ${{ github.sha }}
